### ISSUE TITLE
Pods in CrashLoopBackOff State

### ISSUE THREAD

**Issue by jamesbuckett** [kubespray/kpm-stackanetes#2]
Hello.
.
I have installed a CoreOS Kubernetes cluster on Digital Ocean.
.
Kubernetes version is :+1: 
`core@k8s-master ~ $ kubectl version
Client Version: version.Info{Major:"1", Minor:"2", GitVersion:"v1.2.4", GitCommit:"3eed1e3be6848b877ff80a93da3785d9034d0a4f", GitTreeState:"clean"}
Server Version: version.Info{Major:"1", Minor:"2", GitVersion:"v1.2.4", GitCommit:"3eed1e3be6848b877ff80a93da3785d9034d0a4f", GitTreeState:"clean"}
`
Following instructions listed I set the labels on three nodes : 
kubectl label node 10.134.29.141 persistent-control=yes
kubectl label node 10.134.29.197 non-persistent-control=yes
kubectl label node 10.134.29.243 compute=yes 
.
pip install kpm
kpm deploy stackanetes/init
.
Once running : kubectl get pods,rc,svc --all-namespaces
`core@k8s-master ~ $ kubectl get pods,rc,svc --all-namespaces
NAMESPACE     NAME               READY           STATUS             RESTARTS   AGE
default       glance-init        0/1             CrashLoopBackOff   9          29m
default       keystone-db-sync   0/1             CrashLoopBackOff   9          29m
default       keystone-init      0/1             CrashLoopBackOff   9          29m
default       neutron-init       0/1             CrashLoopBackOff   9          29m
default       nova-init          0/1             CrashLoopBackOff   9          29m
kube-system   kube-ui-v5-kkq5m   1/1             Running            0          18m
NAMESPACE     NAME               DESIRED         CURRENT            AGE
kube-system   kube-ui-v5         1               1                  18m
NAMESPACE     NAME               CLUSTER-IP      EXTERNAL-IP        PORT(S)   AGE
default       kubernetes         10.100.0.1      <none>             443/TCP   1h
kube-system   kube-ui            10.100.38.215   nodes              80/TCP    18m
`

kubectl logs glance-init

`core@k8s-master ~ $ kubectl logs glance-init
INFO:__main__:Kolla config strategy set to: COPY_ONCE
INFO:__main__:Validating config file
INFO:__main__:Copying service configuration files
WARNING:kazoo.client:Connection dropped: socket connection error: Name or service not known
WARNING:kazoo.client:Failed connecting to Zookeeper within the connection retry policy.
Traceback (most recent call last):
  File "/usr/local/bin/kolla_set_configs", line 332, in <module>
    sys.exit(main())
  File "/usr/local/bin/kolla_set_configs", line 327, in main
    execute_config_strategy()
  File "/usr/local/bin/kolla_set_configs", line 271, in execute_config_strategy
    copy_config(config)
  File "/usr/local/bin/kolla_set_configs", line 246, in copy_config
    if validate_source(data):
  File "/usr/local/bin/kolla_set_configs", line 54, in validate_source
    with zk_connection(source) as zk:
  File "/usr/lib64/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "/usr/local/bin/kolla_set_configs", line 86, in zk_connection
    zk.start()
  File "/usr/lib/python2.7/site-packages/kazoo/client.py", line 546, in start
    raise self.handler.timeout_exception("Connection time-out")
kazoo.handlers.threading.KazooTimeoutError: Connection time-out
`

I checked /usr/local/bin and /usr/local/bin/kolla_set_configs is not present.

Does KPM work on CoreOS ?

**Comment by ant31** [comment]
Thanks for report

I tested on gce instances, I ll try again on a baremetal, it s maybe something hardcoded in the resources

What is your primary network interface? eth0?

**Comment by jamesbuckett** [comment]
These are Digital Ocean systems One Public IP and One Private IP
ip a
`2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP group default qlen 1000
    link/ether 04:01:03:dc:47:01 brd ff:ff:ff:ff:ff:ff
    inet 169.254.238.78/16 brd 169.254.255.255 scope link eth0
       valid_lft forever preferred_lft forever
    inet 159.203.222.147/20 brd 159.203.223.255 scope global eth0
       valid_lft forever preferred_lft forever
    inet 10.12.0.9/16 brd 10.12.255.255 scope global eth0
       valid_lft forever preferred_lft forever
    inet6 fe80::601:3ff:fedc:4701/64 scope link
       valid_lft forever preferred_lft forever
3: eth1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP group default qlen 1000
    link/ether 04:01:03:dc:47:02 brd ff:ff:ff:ff:ff:ff
    inet 10.134.29.141/16 brd 10.134.255.255 scope global eth1
       valid_lft forever preferred_lft forever
    inet6 fe80::601:3ff:fedc:4702/64 scope link
       valid_lft forever preferred_lft forever
`
Regards.
