### ISSUE TITLE
kpm error deploying stackanetes/stackanetes

### ISSUE THREAD

**Issue by v1k0d3n** [kubespray/kpm-stackanetes#4]
having issues some issues with deploying this project. i will come back and explore a little more later.

```
$ kpm deploy stackanetes/stackanetes
Traceback (most recent call last):
  File "/usr/local/bin/kpm", line 8, in <module>
    args.func(args)
  File "/Library/Python/2.7/site-packages/kpm/command.py", line 49, in install
    variables=variables)
  File "/Library/Python/2.7/site-packages/kpm/deploy.py", line 83, in deploy
    return _process(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/kpm/deploy.py", line 31, in _process
    packages = registry.generate(package_name, namespace=namespace, version=version, variables=variables)
  File "/Library/Python/2.7/site-packages/kpm/registry.py", line 74, in generate
    r.raise_for_status()
  File "/Library/Python/2.7/site-packages/requests/models.py", line 844, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: https://api.kpm.sh/api/v1/packages/stackanetes/stackanetes/generate
```

**Comment by v1k0d3n** [comment]
i wonder if this has something to do with the network interface? this is on a bare metal installation. i would _think_ that most serious installations of this project would be bare metal or something with a lot of juice. my network interface is **enp0s31f6**. is this a variable that can be modified?

**Comment by ant31** [comment]
I'll look at it. 

Yes, the original stackanetes was tested on very large machines. 

Your issue is due to a bad packaging, I'll review all packages tmrw.
